CREATE TABLE users(
	user_id INTEGER PRIMARY KEY AUTOINCREMENT,
	first_name TEXT NOT NULL,
	last_name TEXT NOT NULL,
	username TEXT NOT NULL UNIQUE,
	password BLOB NOT NULL
);

CREATE TABLE accounts(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	user_id INTEGER NOT NULL,
	site TEXT NOT NULL,
	username TEXT NOT NULL,
	password TEXT NOT NULL,
	FOREIGN KEY(user_id) REFERENCES users(user_id)
);
